version: "3.8"
services:
  api:
    build: "./api"
    ports:
      - "8080:8080"
    env_file: 
      - .env
  db:
    build: "./db"
    ports:
      - "5432:5432"
    volumes: 
      - database-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
  web:
    build: "./web"
    ports: 
      - "80:80"
volumes: 
  database-data: