version: "3.8"
services:
  api:
    build: "./api"
    ports:
      - "8080:8080"
    env_file: 
      - .env
  db:
    build: "./db"
    ports:
      - "27017:27017"
    volumes: 
      - database-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
  # web:
  #   build: "./web"
  #   ports: 
  #     - "80:80"
volumes: 
  database-data: