FROM nginx

## RECIPE MANAGER NGINX WEB SERVER
RUN mkdir /app
COPY ./recipe-manager-client/dist /app
COPY ./recipe-manager-site.conf /etc/nginx/nginx.conf

# Run NGINX
CMD ["nginx", "-g", "daemon off;"]